document.write('<head>');
document.write('<meta http-equiv=content-Type content=tl; charset=gb2312>');
document.write('<link rel=stylesheet href=text.css>');
document.write('<title>辑注类->裴注三国志 http://www.luhui.net 全球最好互动式种源文化传播交流索引平台 lǔ 鲁 huǐ 虺 wén 文 huà 化 wǎng 网</title>');
document.write('</head><SCRIPT language=JavaScript src="/htmledit/images/top.js"></SCRIPT><SCRIPT language=JavaScript src="/htmledit/images/Navigate.js"></SCRIPT><SCRIPT language=javascript src="/htmledit/images/Blank_link.js" type=text/javascript></SCRIPT><SCRIPT language=javascript src="/htmledit/images/Word_Spell.js" type=text/javascript></SCRIPT>');
document.write('<body>');
document.write('<table align=center border=0 cellspacing=0 width=720 cellpadding=0>');
document.write('<tr valign=top>');
document.write('</tr>');
document.write('</table>');
document.write('<table align=center cellspacing=1 width=720 class=t2>');
document.write('<tr><td>');
document.write('<table width=100% cellspacing=0 border=0 class=t3 cellpadding=5>');
document.write('<colgroup span=3 class="pn03 p1"></colgroup>');
document.write('<tr>');
document.write('<td width=*>');
document.write('裴注三国志 '+jno+'</td>');
document.write('<td align=right width=160><a href=index.htm>返回目录</a>　<a href="javascript:window.close()">关闭窗口</a></td>');
document.write('</tr>');
document.write('</table>');
document.write('</td></tr>');
document.write('<tr><td class="pn00 p0">');