document.writeln("<script src=\"http:\/\/s11.cnzz.com\/stat.php?id=2096282&web_id=2096282&show=pic\" language=\"JavaScript\"><\/script>");
document.writeln("")
document.writeln("<!-- Google tag (gtag.js) -->");
document.writeln("<script async src=\'https://www.googletagmanager.com/gtag/js?id=G-P3287V69Y1\'></script>");
document.writeln("<script>");
document.writeln("  window.dataLayer = window.dataLayer || [];");
document.writeln("  function gtag(){dataLayer.push(arguments);}");
document.writeln("  gtag(\'js\', new Date());");
document.writeln("");
document.writeln("  gtag(\'config\', \'G-P3287V69Y1\');");
document.writeln("</script>");
document.writeln("");
document.writeln("");
document.writeln("<script>");
document.writeln("var _hmt = _hmt || [];");
document.writeln("(function() {");
document.writeln("  var hm = document.createElement(\'script\');");
document.writeln("  hm.src = \'https://hm.baidu.com/hm.js?1ff53de6bccef79327d31cb3ab0ee9ff\';");
document.writeln("  var s = document.getElementsByTagName(\'script\')[0]; ");
document.writeln("  s.parentNode.insertBefore(hm, s);");
document.writeln("})();");
document.writeln("</script>");
document.writeln("");
document.writeln("<!--百度自动推送代码开始-->");
document.writeln("<script>");
document.writeln("(function(){");
document.writeln("var bp = document.createElement(\'script\');");
document.writeln("bp.src = \'//push.zhanzhang.baidu.com/push.js\';");
document.writeln("var s = document.getElementsByTagName(\'script\')[0];");
document.writeln("s.parentNode.insertBefore(bp, s);");
document.writeln("})();");
document.writeln("</script>");
document.writeln("<!--百度自动推送代码结束-->");
document.writeln("");
document.writeln("<!-- 网址安全插件开始 -->");
document.writeln("<script type=\'text/javascript\'>");
document.writeln("var _svq_ = _svq_ || [];");
document.writeln("_svq_.push([\'set_api_key\', \'16adflfafads9gf28327005056b68c3d\']);");
document.writeln("_svq_.push([\'set_noicon_class\', \'\']); //链接前不显示任何图标，如果需要显示，请去掉这句");
document.writeln("_svq_.push([\'set_nopopup_class\', \'-sv-no-popup\']); ");
document.writeln("_svq_.push([\'check_page\']);");
document.writeln("(function(){");
document.writeln("var aq = document.createElement(\'script\');");
document.writeln("aq.type = \'text/javascript\'; ");
document.writeln("aq.async = true;");
document.writeln("aq.charset = \'utf-8\';");
document.writeln("aq.src = \'http://openapi.anquan.org/static/aq.js\';");
document.writeln("var s = document.getElementsByTagName(\'script\')[0];");
document.writeln("s.parentNode.insertBefore(aq, s); ");
document.writeln("})();");
document.writeln("</script>");
document.writeln("<!-- 网址安全插件结束 --> ");